### ISSUE TITLE
real world example

### ISSUE THREAD

**Issue by meikestone** [oaeproject/SAMLParser#1]
Hello,

can't get work the SAMLParser. Please can you provide a real world example or refine the documentation? Is XML-Data e.g. the base64 encoded value from the SAMLResponse (hidden filed in POST, or only the CipherValue from the SAML message?)

How are the <idpPublicKey> <spPublicKey> <spPrivateKey> <XML data> defined?

Must I paste all parameters in the command line or may I use `$(cat <key|data> file)`?

Examples (I used plain XML SAMLResponse in test_data.txt):

 ```
$JAVA_HOME/bin/java -jar target/org.sakaiproject.Hilary.SAMLParser-1.0-SNAPSHOT-jar-with-dependencies.jar idp-signing.key sp-pubKey.pem sp-key.pem $(cat test_data.txt)
Bad Base64 input character at 2: 45(decimal)
Exception in thread "main" java.lang.NullPointerException
        at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:106)
        at org.opensaml.xml.security.SecurityHelper.buildJavaX509Cert(SecurityHelper.java:482)
        at org.sakaiproject.SAMLParser.SAMLParser.buildCredentials(SAMLParser.java:86)
        at org.sakaiproject.SAMLParser.SAMLParser.<init>(SAMLParser.java:55)
        at org.sakaiproject.SAMLParser.App.main(App.java:80)
```

 ```
$JAVA_HOME/bin/java -jar target/org.sakaiproject.Hilary.SAMLParser-1.0-SNAPSHOT-jar-with-dependencies.jar "$(cat idp-signing.key)" "$(cat  sp-pubKey.pem)" "$(cat sp-privkey.pem)" "$(cat test_data.txt)" 'plain' 'plain'
Bad Base64 input character at 0: 45(decimal)
Exception in thread "main" java.lang.NullPointerException
        at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:106)
        at org.opensaml.xml.security.SecurityHelper.buildJavaX509Cert(SecurityHelper.java:482)
        at org.sakaiproject.SAMLParser.SAMLParser.buildCredentials(SAMLParser.java:86)
        at org.sakaiproject.SAMLParser.SAMLParser.<init>(SAMLParser.java:55)
        at org.sakaiproject.SAMLParser.App.main(App.java:80)
```

**Comment by liomthechef** [comment]
using powershell as an example
$pub = cat pub.pem
$key = cat key.pem
$assertion = cat base64encoded.txt

java -jar org.sakaiproject.Hilary.SAMLParser-1.0-SNAPSHOT-jar-with-dependencies.jar $idppub $pub $key $assertion 'base64'

note that I could not get my xml formatted input working and I don't know why, I resorted to base64 encoding it and that worked well.

**Comment by ravikarthig** [comment]
Hi,
Even I am facing the above issue but for the step 87 in SAMLParser.java i.e. while private key is parsed, i guess the format is not understood. I tried pkcs8,der and pem but none of them work. Could you please share the format of the private key used (file format, should it contain the header ---Begin Private Key----, is /n permitted,etc)

Exception details
 Bad Base64 input character at 0: 45(decimal)
Exception in thread "main" java.lang.NullPointerException
        at java.io.ByteArrayInputStream.<init>(Unknown Source)
        at org.apache.commons.ssl.PEMUtil.decode(PEMUtil.java:91)
        at org.apache.commons.ssl.PKCS8Key.<init>(PKCS8Key.java:150)
        at org.opensaml.xml.security.SecurityHelper.decodePrivateKey(SecurityHelper.java:466)
        at org.opensaml.xml.security.SecurityHelper.buildJavaPrivateKey(SecurityHelper.java:575)
        at org.opensaml.xml.security.SecurityHelper.buildJavaRSAPrivateKey(SecurityHelper.java:545)
        at org.sakaiproject.SAMLParser.SAMLParser.buildCredentials(SAMLParser.java:87)
        at org.sakaiproject.SAMLParser.SAMLParser.<init>(SAMLParser.java:55)
        at org.sakaiproject.SAMLParser.App.main(App.java:80)

**Comment by lubumbax** [comment]
I couldn't make it work in any way by passing environment variables. 
I managed to make it work though (Mac OS X at least) by introducing two changes into that code:

- pass file names as parameters and parse them from Java
- make sure that both '\r' and '\n' are removed from data in those public/private key files and also from the signature in the assertion

After those changes it worked. Here is how I run it:

`java -jar $SAML_PARSER_JAR idp_signing.pem sp.pem sp.key assertion.xml`

I will see if I find time to submit a PR.

**Comment by anishnath** [comment]
Online version of SAML parser https://8gwifi.org/samlverifysign.jsp
